jenkins:  'https://10.96.112.150'
username: 'Anupama'
password: 'ampliseq@321'

repo:'https://github.com/AnupamaRudra/autojob'
scm-username: 'AnupamaRudra'
scm-password: 'AR1998rocks!'

template: first
namefmt: '{shortref}'
overwrite: true
enable: true
